server:
  port: 8081

spring:
  application:
    name: auth-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://ep-hidden-bar-azmsarvo-pooler.c-3.ap-southeast-1.aws.neon.tech/auth_db?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_4NeM5xPfaAsY
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:ChangeMeToA32ByteMinimumSecretKey!}
  expiration: ${JWT_EXPIRATION:900000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

openapi:
  service:
    title: Auth Service API
    version: 1.0.0

logging:
  level:
    root: INFO
    web: INFO

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
