server:
  port: 8081

spring:
  application:
    name: auth-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://concert-postgres:5432/auth_db

openapi:
  service:
    title: Auth Service API
    version: 1.0.0

logging:
  level:
    root: INFO
    web: INFO

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/ # Địa chỉ của Eureka Server
#    fetch-registry: true
#    register-with-eureka: true
#  instance:
#    prefer-ip-address: true