server:
  port: 8085

spring:
  application:
    name: notification-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://concert-postgres:5432/notification_db

openapi:
  service:
    title: Notification Service API
    version: 1.0.0

logging:
  level:
    root: INFO
    web: INFO

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
