spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    discovery:
      client:
        simple:
          instances:
            auth-service:
              - uri: http://localhost:8081
            core-service:
              - uri: http://localhost:8082
            booking-service:
              - uri: http://localhost:8083
            payment-service:
              - uri: http://localhost:8084
            notification-service:
              - uri: http://localhost:8085
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://127.0.0.1:5173"
              - "http://localhost:3000"
              - "http://localhost:8080"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
              - "PATCH"
            allowedHeaders: "*"
            exposedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/auth/(?<segment>.*), /auth/${segment}

        - id: core-service
          uri: lb://core-service
          predicates:
            - Path=/api/v1/core/**
          filters:
            - RewritePath=/api/v1/core/(?<segment>.*), /${segment}

        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/v1/bookings/**
          filters:
            - RewritePath=/api/v1/bookings/(?<segment>.*), /bookings/${segment}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 50
                redis-rate-limiter.burstCapacity: 100
                key-resolver: "#{@ipKeyResolver}"

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - RewritePath=/api/v1/payments/(?<segment>.*), /payments/${segment}

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notification/**
          filters:
            - RewritePath=/api/v1/notification/(?<segment>.*), /${segment}

        # ===== SWAGGER API DOCS ROUTING =====
        - id: auth-service-docs
          uri: http://localhost:8081
          predicates:
            - Path=/v3/api-docs/auth-service
          filters:
            - SetPath=/v3/api-docs


        - id: core-service-docs
          uri: http://localhost:8082
          predicates:
            - Path=/v3/api-docs/core-service
          filters:
            - SetPath=/v3/api-docs


        - id: booking-service-docs
          uri: http://localhost:8083
          predicates:
            - Path=/v3/api-docs/booking-service
          filters:
            - SetPath=/v3/api-docs


        - id: payment-service-docs
          uri: http://localhost:8084
          predicates:
            - Path=/v3/api-docs/payment-service
          filters:
            - SetPath=/v3/api-docs


        - id: notification-service-docs
          uri: http://localhost:8085
          predicates:
            - Path=/v3/api-docs/notification-service
          filters:
            - SetPath=/v3/api-docs



springdoc:

  swagger-ui:
    path: /swagger-ui.html

    urls:

      - name: Auth Service
        url: /v3/api-docs/auth-service

      - name: Core Service
        url: /v3/api-docs/core-service

      - name: Booking Service
        url: /v3/api-docs/booking-service

      - name: Payment Service
        url: /v3/api-docs/payment-service

      - name: Notification Service
        url: /v3/api-docs/notification-service