server:
  port: 8083

spring:
  application:
    name: booking-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://concert-postgres:5432/booking_db

openapi:
  service:
    title: Booking Service API
    version: 1.0.0

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 900000        # 15 phút (Access Token)
  refresh-expiration: 604800000 # 7 ngày (Refresh Token)

logging:
  level:
    root: INFO
    web: INFO

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
