server:
  port: 8084

spring:
  application:
    name: payment-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://concert-postgres:5432/payment_db

openapi:
  service:
    title: Payment Service API
    version: 1.0.0

logging:
  level:
    root: INFO
    web: INFO

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
